---
- name: Create Caddy home
  file: path=/var/lib/caddy state=directory

- name: Create Caddy user
  user: name=caddy system=yes home=/var/lib/caddy

- name: Set perms
  file: path=/var/lib/caddy state=directory owner=caddy mode=0700

- name: Download caddy
  get_url: url=https://caddyserver.com/download/build?os=linux&arch=amd64 dest=/tmp/caddy.tar.gz

- name: Extract caddy
  command: tar xvf /tmp/caddy.tar.gz -C /tmp/

- name: Caddy to bin
  command: mv /tmp/caddy /usr/bin/

- name: Caddy privilege
  command: setcap cap_net_bind_service=+ep /usr/bin/caddy

- name: Create Caddy config dir
  file: path=/etc/caddy state=directory

- name: Create Caddy config file
  template: src=Caddyfile dest=/etc/caddy/Caddyfile

- name: Systemd
  template: src=caddy.service dest=/etc/systemd/system/caddy.service

- name: Create web dir
  file: path=/var/www state=directory

- name: Activation
  command: systemctl enable caddy.service

- name: Download the site
  git: repo={{ site_repo }} dest=/var/www

- name: Start caddy
  command: systemctl start caddy.service
