---
- name: Create Caddy user
  user: name=caddy system=yes home=/var/lib/caddy

- name: Download caddy
  get_url: url=https://caddyserver.com/download/build?os=linux&arch=amd64 dest=/tmp/caddy.tar.gz

- name: Extract caddy
  unarchive: src=/tmp/caddy.tar.gz dest=/tmp/ copy=no

- name: Caddy to bin
  command: mv /tmp/caddy /usr/bin/ creates=/usr/bin/caddy

- name: Caddy privilege
  command: setcap cap_net_bind_service=+ep /usr/bin/caddy

- name: Create Caddy config dir
  file: path=/etc/caddy state=directory

- name: Create Caddy config file
  template: src=Caddyfile dest=/etc/caddy/Caddyfile

- name: Create web dir
  file: path=/var/www state=directory

- name: Install git
  apt: name=git update_cache=yes
  when: install_git

- name: Download the site
  git: repo={{ site_repo }} dest=/var/www
  when: site_repo

- name: Systemd
  template: src=caddy.service dest=/etc/systemd/system/caddy.service
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Start Caddy site
  service: name=caddy state=started enabled=yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
