---
- include: packages-{{ ansible_pkg_mgr }}.yml

- name: Create Caddy user
  user: name={{ caddy_user }} system=yes createhome=yes home={{ caddy_home }}

- name: Get all Caddy releases
  get_url: url=https://api.github.com/repos/mholt/caddy/git/refs/tags dest={{ caddy_home }}/releases.txt force=yes
  when: caddy_update
  register: caddy_releases_cache

- name: Set Caddy features
  copy: content="{{caddy_features}}" dest={{ caddy_home }}/features.txt
  when: caddy_update
  register: caddy_features_cache

- name: Download Caddy
  get_url: url=https://caddyserver.com/download/build?os=linux&arch=amd64&features={{caddy_features}} dest={{ caddy_home }}/caddy.tar.gz force=yes
  when: caddy_releases_cache.changed or caddy_features_cache.changed
  register: caddy_binary_cache

- name: Download Caddy
  get_url: url=https://caddyserver.com/download/build?os=linux&arch=amd64&features={{caddy_features}} dest={{ caddy_home }}/caddy.tar.gz

- name: Extract Caddy
  unarchive: src={{ caddy_home }}/caddy.tar.gz dest={{ caddy_home }} copy=no
  when: caddy_binary_cache.changed

- name: Extract Caddy
  unarchive: src={{ caddy_home }}/caddy.tar.gz dest={{ caddy_home }} creates={{ caddy_home }}/caddy copy=no

- name: Copy Caddy Binary
  copy: src={{ caddy_home }}/caddy dest=/usr/bin/ mode=0755 remote_src=True
  notify: Restart Caddy

- name: Check if the binary can bind to TCP port <1024
  shell: getcap /usr/bin/caddy | grep cap_net_bind_service
  failed_when: False
  changed_when: False
  when: not caddy_init_system or caddy_init_system == "upstart"
  register: caddy_bind_cap

- name: Set capability on the binary file to be able to bind to TCP port <1024
  command: setcap cap_net_bind_service=+ep /usr/bin/caddy
  when: not caddy_init_system or caddy_init_system == "upstart" and caddy_bind_cap.rc > 0

- name: Create directories
  file: path={{ item }} state=directory owner={{ caddy_user }} mode=0770
  with_items:
    - /etc/caddy
    - /etc/ssl/caddy
    - /var/www

- name: Create Caddyfile
  copy: content="{{caddy_config}}" dest=/etc/caddy/Caddyfile
  notify: Restart Caddy

- name: Upstart service
  template: src=caddy.conf dest=/etc/init/caddy.conf
  ignore_errors: yes
  when: not caddy_init_system or caddy_init_system == "upstart"
  notify: Restart Caddy

# this may also be copied later on - currently packaged file does not contain the features
- name: Systemd service | get config from github
  get_url: url=https://raw.githubusercontent.com/mholt/caddy/master/dist/init/linux-systemd/caddy.service dest=/etc/systemd/system/caddy.service mode=0755
  ignore_errors: yes
  when: not caddy_init_system or caddy_init_system == "systemd"
  notify: Reload systemd service file

- name: Systemd service | set ExecStart
  lineinfile: 
    state: present
    dest: /etc/systemd/system/caddy.service
    regexp: '^ExecStart\='
    line: 'ExecStart=/usr/bin/caddy -log stdout -agree=true -email {{ caddy_email }} -conf=/etc/caddy/Caddyfile -root=/var/www'
  when: not caddy_init_system or caddy_init_system == "systemd"
  notify: Reload systemd service file

- name: Start Caddy service
  service: name=caddy state=started enabled=yes
